 export const products = [
  {
    id: 1,
    brand: "AKATSUKI SYNDICATE",
    category: "STREETWEAR",
    title: "Heavyweight Cloud Cloak Hoodie (Matte Black)",
    rating: 4.8,
    reviews: 124,
    originalPrice: "$129.99",
    price: "$89.99",
    discount: "-30% OFF",
    tags: ["BEST SELLER", "LIMITED RUN"],
    lowStock: false,
    image: "/images/Akatsuki.jpg"
  },
  {
    id: 2,
    brand: "ANBU OPS",
    category: "PROP REPLICA",
    title: "Porcelain Shadow Mask - Itachi Edition",
    rating: 4.9,
    reviews: 88,
    originalPrice: null,
    price: "$145.00",
    discount: null,
    tags: ["HANDCRAFTED", "MATTE FINISH"],
    lowStock: true,
    stockCount: 3,
    image: "/images/Anbu.webp"
  },
  {
    id: 3,
    brand: "UCHIHA ARCHIVES",
    category: "ACCESSORIES",
    title: "Mangekyou Sharingan Obsidian Signet Ring",
    rating: 5.0,
    reviews: 42,
    originalPrice: "$85.00",
    price: "$64.99",
    discount: "-24% OFF",
    tags: ["ARTISAN", "TITANIUM"],
    lowStock: false,
    image: "/images/Sharingan.webp"
  },
  {
    id: 4,
    brand: "GHOST OF UCHIHA",
    category: "WEAPONS",
    title: "Madara's Gunbai War Fan (1:1 Scale Metal)",
    rating: 4.7,
    reviews: 31,
    originalPrice: "$399.99",
    price: "$299.99",
    discount: "-25% OFF",
    tags: ["COLLECTOR'S TIER", "HEAVYWEIGHT"],
    lowStock: false,
    image: "/images/Gunbai.jpeg"
  },
  {
    id: 5,
    brand: "HIDDEN LEAF ELITE",
    category: "COLLECTIBLE",
    title: "Minato's Hiraishin Kunai (24k Gold Plated Edition)",
    rating: 5.0,
    reviews: 156,
    originalPrice: "$220.00",
    price: "$180.00",
    discount: "-18% OFF",
    tags: ["PREMIUM TIER", "VAULT EXCLUSIVE"],
    lowStock: true,
    stockCount: 2,
    image: "/images/Kunai.jpg"
  },
  {
    id: 6,
    brand: "CURSED ARCHIVES",
    category: "PROP REPLICA",
    title: "Ryomen Sukuna Cursed Finger (Resin Cast)",
    rating: 4.6,
    reviews: 95,
    originalPrice: "$60.00",
    price: "$45.00",
    discount: "-25% OFF",
    tags: ["BEST SELLER"],
    lowStock: false,
    image: "/images/Sukuna.webp"
  },
  {
    id: 7,
    brand: "ESPADA SYNDICATE",
    category: "APPAREL",
    title: "Las Noches Heavyweight Bomber (Charcoal)",
    rating: 4.8,
    reviews: 67,
    originalPrice: null,
    price: "$110.00",
    discount: null,
    tags: ["NEW ARRIVAL"],
    lowStock: false,
    image: "/images/Fortress.jpg"
  },
  {
    id: 8,
    brand: "HASHIRA FORGE",
    category: "KATANA",
    title: "Sun Breathing Nichirin (Matte Black Carbon)",
    rating: 4.9,
    reviews: 210,
    originalPrice: "$299.99",
    price: "$250.00",
    discount: "-16% OFF",
    tags: ["ARTISAN", "1:1 SCALE"],
    lowStock: true,
    stockCount: 4,
    image: "/images/Sword.webp"
  },
  {
    id: 9,
    brand: "PARADIS COMMAND",
    category: "JEWELRY",
    title: "Wings of Freedom Titanium Pendant",
    rating: 4.7,
    reviews: 184,
    originalPrice: "$75.00",
    price: "$55.00",
    discount: "-26% OFF",
    tags: ["BEST SELLER"],
    lowStock: false,
    image: "/images/Wings.png"
  },
  {
    id: 10,
    brand: "METEOR CITY",
    category: "ACCESSORIES",
    title: "Phantom Troupe Artisan Keycap Set",
    rating: 4.9,
    reviews: 53,
    originalPrice: null,
    price: "$85.00",
    discount: null,
    tags: ["LIMITED EDITION", "CHERRY MX"],
    lowStock: false,
    image: "/images/Keys.jpg"
  },
  {
    id: 11,
    brand: "STATE ALCHEMIST",
    category: "ACCESSORIES",
    title: "Flamel Transmutation Pocket Watch (Vintage Brass)",
    rating: 4.8,
    reviews: 112,
    originalPrice: null,
    price: "$120.00",
    discount: null,
    tags: ["VAULT EXCLUSIVE"],
    lowStock: true,
    stockCount: 7,
    image: "/images/Watch.webp"
  },
  {
    id: 12,
    brand: "ZENIN OUTCAST",
    category: "STREETWEAR",
    title: "Heavenly Restriction Compression Top",
    rating: 4.7,
    reviews: 89,
    originalPrice: "$60.00",
    price: "$45.00",
    discount: "-25% OFF",
    tags: ["PERFORMANCE"],
    lowStock: true,
    stockCount: 5,
    image: "/images/Toji.webp"
  }
];